language: node_js
node_js:
  - "10"
cache:
  directories:
    - ./frontend/node_modules
script:
  - cd frontend
  - npm install
  - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id: "$AWS_KEY_ID"
    secret_access_key: "$AWS_KEY_SECRET"
    bucket: cs268
    region: us-east-1
    local_dir: build
    skip_cleanup: true
    acl: public_read
