version: "3"
services:
  db:
    container_name: pinball-db
    image: "bitnami/mongodb:latest"
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=tester
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=pinball
      - MONGODB_EXTRA_FLAGS=--quiet
